# Generated by Django 5.0.1 on 2024-02-02 09:27

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_image.jpg', upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
