# Generated by Django 5.0.1 on 2024-02-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
    ]
