# Generated by Django 4.2.8 on 2024-11-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='streest',
            new_name='street',
        ),
    ]
